export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_ITEM_SHOP = 'ADD_ITEM_SHOP';
export const REMOVE_ITEM_SHOP = 'REMOVE_ITEM_SHOP';
export const INIT_STATE = 'INIT_STATE';
export const INIT_LOCAL_STORAGE = 'INIT_LOCAL_STORAGE';